pipeline {
    agent any

    tools {
        // Install the Maven version configured as "M3" and add it to the path.
        maven "M3"
    }

    parameters {
            string(name: 'personId', defaultValue: '2', description: 'Person ID')
            string(name: 'filmId', defaultValue: '7', description: 'Film ID')
            string(name: 'statusCode', defaultValue: '404', description: 'Status Code')
    }

    stages {
        stage('Checkout') {
            steps {
                echo 'Getting repository info...'
                git branch: 'main', url: 'https://github.com/GbtCesarAlex86/CI_Practice-TAE-Academy.git'
            }
        }

        stage('SettingUp Environment'){
            steps{
                echo 'Building...'
                bat 'mvn clean'
            }
        }

        stage('Running Tests') {
            steps {
                echo 'Using personId = ${params.personId}, filmId = ${params.filmId}, statusCode = ${params.statusCode}'
                bat "mvn test -DsuiteXmlFile=src/test/resources/testng.xml -DpersonId=${params.personId} -DfilmId=${params.filmId} -DstatusCode=${params.statusCode}"
            }
        }

        stage('Generating Allure Report') {
            steps {
                echo 'Generating'
                bat 'mvn allure:report'
            }
        }
    }

    post {
        always {
            allure([
                includeProperties: false,
                jdk:'',
                properties:[],
                reportBuildPolicy:'ALWAYS',
                results:[[path: 'target/allure-results']]
                ])
            cleanWs()
        }

        success{
            echo 'EXECUTION SUCCEED'
        }

        failure {
            echo 'The execution failed, please check the results'
            mail to: 'cesar.tipan@globant.com',
                 subject: "Failed Pipeline: ${currentBuild.fullDisplayName}",
                 body: "Something is wrong with ${env.BUILD_URL}"
        }
    }
}