pipeline {
    agent any

    environment {
        MY_VARIABLE = 'my value'
    }

    stages {
        stage('Build') {
            steps {
                echo 'Building...'
                bat 'mvn clean install'
            }
        }
        stage('Run') {
            matrix {
                axes {
                    axis {
                        name 'MY_VARIABLE'
                        values 'value1', 'value2', 'value3'
                    }
                }
                stages {
                    stage('Run with different values') {
                        steps {
                            echo 'Running...'
                            echo "MY_VARIABLE is ${env.MY_VARIABLE}"
                            bat 'mvn exec:java -Dexec.mainClass=com.globant.Main'
                        }
                    }
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
        failure {
            mail to: 'cesar.tipan@globant.com',
                 subject: "Failed Pipeline: ${currentBuild.fullDisplayName}",
                 body: "Something is wrong with ${env.BUILD_URL}"
        }
    }
}