pipeline {
    agent any

    tools {
        // Install the Maven version configured as "M3" and add it to the path.
        maven "M3"
    }

    parameters {
            string(name: 'personId', defaultValue: '2', description: 'Person ID')
            string(name: 'skinColor', defaultValue: 'gold', description: 'Skin Color')
            string(name: 'filmCount', defaultValue: '6', description: 'Film Count')
            string(name: 'filmId', defaultValue: '7', description: 'Film ID')
            string(name: 'statusCode', defaultValue: '404', description: 'Status Code')
    }

    stages {
        stage('Checkout') {
            steps {
                echo 'Getting repository info...'
                git branch: 'main', url: 'https://github.com/GbtCesarAlex86/CI_Practice-TAE-Academy.git'
            }
        }

        stage('SettingUp Environment'){
            steps{
                echo 'Building...'
                bat 'mvn clean verify'
            }
        }

        stage('Running Tests') {
            steps {
                bat "mvn test -DsuiteXmlFile=src/test/resources/testng.xml -DpersonId=${params.personId} -DskinColor=${params.skinColor} -DfilmCount=${params.filmCount} -DfilmId=${params.filmId} -DstatusCode=${params.statusCode}"
            }
        }
    }

    post {
        always {
            cleanWs()
        }
        failure {
            mail to: 'cesar.tipan@globant.com',
                 subject: "Failed Pipeline: ${currentBuild.fullDisplayName}",
                 body: "Something is wrong with ${env.BUILD_URL}"
        }
    }
}